-- Security Note: Demo credentials and hardcoded user updates have been removed for security reasons.
-- System admin accounts should be created through the proper signup process
-- or using environment variables for development purposes only.