-- Security Note: Demo credentials have been removed for security reasons.
-- Admin accounts should be created through the proper signup process
-- or using environment variables for development purposes only.